version: '3.9'

services:
  api-tarefas:
    image: pietrineo/devops-pucrs-app:latest
    container_name: api-tarefas-hml
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=homologacao
